// SPDX-License-Identifier: GPL-2.0-or-later
// GENERATED by scripts/esi2coupler.py -- DO NOT EDIT BY HAND
//   source ESI : INOVANCE_GL20_RTU_ECT32_3.1.2.0.xml
//   sha256     : 4a47c9cca1c304ecf55992e1b253c40708f2d4d3650fde605431deefdef8a3e1
//   device     : GL20(GL20S)-RTU-ECT32
// Regenerate with:
//   ./scripts/esi2coupler.py --esi <esi> --family gl20

#ifndef _LCEC_MDP_GL20_H_
#define _LCEC_MDP_GL20_H_

#include "lcec_mdp_coupler.h"

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__0404etp_5v_tx_entries[] = {
    {0x6001, 1, 1, 8, 0, "Digital input CH0-8bit"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__0404etp_5v_rx_entries[] = {
    {0x7001, 1, 1, 8, 0, "Digital output CH0-8bit"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__0808etn_tx_entries[] = {
    {0x6001, 1, 1, 8, 0, "Digital input CH0-8bit"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__0808etn_rx_entries[] = {
    {0x7001, 1, 1, 8, 0, "Digital output CH0-8bit"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__3232etn_tx_entries[] = {
    {0x6001, 1, 1, 8, 0, "Digital input CH0-8bit"},
    {0x6001, 1, 2, 8, 0, "Digital input CH1-8bit"},
    {0x6001, 1, 3, 8, 0, "Digital input CH2-8bit"},
    {0x6001, 1, 4, 8, 0, "Digital input CH3-8bit"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__3232etn_rx_entries[] = {
    {0x7001, 1, 1, 8, 0, "Digital output CH0-8bit"},
    {0x7001, 1, 2, 8, 0, "Digital output CH1-8bit"},
    {0x7001, 1, 3, 8, 0, "Digital output CH2-8bit"},
    {0x7001, 1, 4, 8, 0, "Digital output CH3-8bit"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__0032etp_tx_entries[] = {
    {0xa000, 1, 1, 16, 0, "0032ETP Module Diagnosis Information"},
    {0xa000, 1, 2, 16, 0, "0032ETP DO-CH0 Diagnosis Information"},
    {0xa000, 1, 3, 16, 0, "0032ETP DO-CH1 Diagnosis Information"},
    {0xa000, 1, 4, 16, 0, "0032ETP DO-CH2 Diagnosis Information"},
    {0xa000, 1, 5, 16, 0, "0032ETP DO-CH3 Diagnosis Information"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__0032etp_rx_entries[] = {
    {0x7001, 1, 1, 8, 0, "Digital output CH0-8bit"},
    {0x7001, 1, 2, 8, 0, "Digital output CH1-8bit"},
    {0x7001, 1, 3, 8, 0, "Digital output CH2-8bit"},
    {0x7001, 1, 4, 8, 0, "Digital output CH3-8bit"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__0032etp_m_tx_entries[] = {
    {0xa000, 1, 1, 16, 0, "0032ETP-M Module Diagnosis Information"},
    {0xa000, 1, 2, 16, 0, "0032ETP-M DO-CH0 Diagnosis Information"},
    {0xa000, 1, 3, 16, 0, "0032ETP-M DO-CH1 Diagnosis Information"},
    {0xa000, 1, 4, 16, 0, "0032ETP-M DO-CH2 Diagnosis Information"},
    {0xa000, 1, 5, 16, 0, "0032ETP-M DO-CH3 Diagnosis Information"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__0032etp_m_rx_entries[] = {
    {0x7001, 1, 1, 8, 0, "Digital output CH0-8bit"},
    {0x7001, 1, 2, 8, 0, "Digital output CH1-8bit"},
    {0x7001, 1, 3, 8, 0, "Digital output CH2-8bit"},
    {0x7001, 1, 4, 8, 0, "Digital output CH3-8bit"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__3200end_tx_entries[] = {
    {0x6001, 1, 1, 8, 0, "Digital input CH0-8bit"},
    {0x6001, 1, 2, 8, 0, "Digital input CH1-8bit"},
    {0x6001, 1, 3, 8, 0, "Digital input CH2-8bit"},
    {0x6001, 1, 4, 8, 0, "Digital input CH3-8bit"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__0032etn_tx_entries[] = {
    {0xa000, 1, 1, 16, 0, "0032ETN Module Diagnosis Information"},
    {0xa000, 1, 2, 16, 0, "0032ETN DO-CH0 Diagnosis Information"},
    {0xa000, 1, 3, 16, 0, "0032ETN DO-CH1 Diagnosis Information"},
    {0xa000, 1, 4, 16, 0, "0032ETN DO-CH2 Diagnosis Information"},
    {0xa000, 1, 5, 16, 0, "0032ETN DO-CH3 Diagnosis Information"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__0032etn_rx_entries[] = {
    {0x7001, 1, 1, 8, 0, "Digital output CH0-8bit"},
    {0x7001, 1, 2, 8, 0, "Digital output CH1-8bit"},
    {0x7001, 1, 3, 8, 0, "Digital output CH2-8bit"},
    {0x7001, 1, 4, 8, 0, "Digital output CH3-8bit"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__0008er_tx_entries[] = {
    {0xa000, 1, 1, 16, 0, "0008ER Moudle Diagnosis information"},
    {0xa000, 1, 2, 16, 0, "0008ER CH0 Diagnosis information"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__0008er_rx_entries[] = {
    {0x7001, 1, 1, 8, 0, "Digital output CH0-8bit"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__0004er_tx_entries[] = {
    {0xa000, 1, 1, 16, 0, "0004ER Moudle Diagnosis information"},
    {0xa000, 1, 2, 16, 0, "0004ER CH0 Diagnosis information"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__0004er_rx_entries[] = {
    {0x7001, 1, 1, 8, 0, "Digital output CH0-8bit"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__0004etp_2a_tx_entries[] = {
    {0xa000, 1, 1, 16, 0, "0004ETP-2A Module Diagnosis Information"},
    {0xa000, 1, 2, 16, 0, "0004ETP-2A CH0 Diagnosis Information"},
    {0xa000, 1, 3, 16, 0, "0004ETP-2A CH1 Diagnosis Information"},
    {0xa000, 1, 4, 16, 0, "0004ETP-2A CH2 Diagnosis Information"},
    {0xa000, 1, 5, 16, 0, "0004ETP-2A CH3 Diagnosis Information"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__0004etp_2a_rx_entries[] = {
    {0x7001, 1, 1, 8, 0, "Digital output CH0-8bit"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__0008etn_tx_entries[] = {
    {0xa000, 1, 1, 16, 0, "0008ETN Module Diagnosis Information"},
    {0xa000, 1, 2, 16, 0, "0008ETN CH0 Diagnosis Information"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__0008etn_rx_entries[] = {
    {0x7001, 1, 1, 8, 0, "Digital output CH0-8bit"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__0008etp_tx_entries[] = {
    {0xa000, 1, 1, 16, 0, "0008ETP Module Diagnosis Information"},
    {0xa000, 1, 2, 16, 0, "0008ETP CH0 Diagnosis Information"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__0008etp_rx_entries[] = {
    {0x7001, 1, 1, 8, 0, "Digital output CH0-8bit"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__1600end_tx_entries[] = {
    {0x6001, 1, 1, 8, 0, "Digital input CH0-8bit"},
    {0x6001, 1, 2, 8, 0, "Digital input CH1-8bit"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__1600end_5v_tx_entries[] = {
    {0x6001, 1, 1, 8, 0, "Digital input CH0-8bit"},
    {0x6001, 1, 2, 8, 0, "Digital input CH1-8bit"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__0800end_tx_entries[] = {
    {0x6001, 1, 1, 8, 0, "Digital input CH0-8bit"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__0800ena_tx_entries[] = {
    {0x6001, 1, 1, 8, 0, "Digital input CH0-8bit"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__0016etn_tx_entries[] = {
    {0xa000, 1, 1, 16, 0, "0016ETN Module Diagnosis Information"},
    {0xa000, 1, 2, 16, 0, "0016ETN CH0 Diagnosis Information"},
    {0xa000, 1, 3, 16, 0, "0016ETN CH1 Diagnosis Information"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__0016etn_rx_entries[] = {
    {0x7001, 1, 1, 8, 0, "Digital output CH0-8bit"},
    {0x7001, 1, 2, 8, 0, "Digital output CH1-8bit"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__0016etp_tx_entries[] = {
    {0xa000, 1, 1, 16, 0, "0016ETP Module Diagnosis Information"},
    {0xa000, 1, 2, 16, 0, "0016ETP CH0 Diagnosis Information"},
    {0xa000, 1, 3, 16, 0, "0016ETP CH1 Diagnosis Information"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__0016etp_rx_entries[] = {
    {0x7001, 1, 1, 8, 0, "Digital output CH0-8bit"},
    {0x7001, 1, 2, 8, 0, "Digital output CH1-8bit"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__0016etp_5v_tx_entries[] = {
    {0xa000, 1, 1, 16, 0, "0016ETP-5V Module Diagnosis Information"},
    {0xa000, 1, 2, 16, 0, "0016ETP-5V CH0 Diagnosis Information"},
    {0xa000, 1, 3, 16, 0, "0016ETP-5V CH1 Diagnosis Information"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__0016etp_5v_rx_entries[] = {
    {0x7001, 1, 1, 8, 0, "Digital output CH0-8bit"},
    {0x7001, 1, 2, 8, 0, "Digital output CH1-8bit"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__8adv_tx_entries[] = {
    {0x6000, 1, 1, 16, 0, "8ADV CH0"},
    {0x6000, 1, 2, 16, 0, "8ADV CH1"},
    {0x6000, 1, 3, 16, 0, "8ADV CH2"},
    {0x6000, 1, 4, 16, 0, "8ADV CH3"},
    {0x6000, 1, 5, 16, 0, "8ADV CH4"},
    {0x6000, 1, 6, 16, 0, "8ADV CH5"},
    {0x6000, 1, 7, 16, 0, "8ADV CH6"},
    {0x6000, 1, 8, 16, 0, "8ADV CH7"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__8adi_tx_entries[] = {
    {0x6000, 1, 1, 16, 0, "8ADI CH0"},
    {0x6000, 1, 2, 16, 0, "8ADI CH1"},
    {0x6000, 1, 3, 16, 0, "8ADI CH2"},
    {0x6000, 1, 4, 16, 0, "8ADI CH3"},
    {0x6000, 1, 5, 16, 0, "8ADI CH4"},
    {0x6000, 1, 6, 16, 0, "8ADI CH5"},
    {0x6000, 1, 7, 16, 0, "8ADI CH6"},
    {0x6000, 1, 8, 16, 0, "8ADI CH7"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__4ad_tx_entries[] = {
    {0x6000, 1, 1, 16, 0, "AD CH0"},
    {0x6000, 1, 2, 16, 0, "AD CH1"},
    {0x6000, 1, 3, 16, 0, "AD CH2"},
    {0x6000, 1, 4, 16, 0, "AD CH3"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__4ad_h_tx_entries[] = {
    {0x6000, 1, 1, 16, 0, "4AD-H CH0"},
    {0x6000, 1, 2, 16, 0, "4AD-H CH1"},
    {0x6000, 1, 3, 16, 0, "4AD-H CH2"},
    {0x6000, 1, 4, 16, 0, "4AD-H CH3"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__4ad_h_rx_entries[] = {
    {0x7000, 1, 1, 16, 0, "4AD-H Control Word"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__8dav_tx_entries[] = {
    {0xa000, 1, 1, 16, 0, "8DAV Module Diagnosis Information"},
    {0xa000, 1, 2, 16, 0, "8DAV CH0 Diagnosis Information"},
    {0xa000, 1, 3, 16, 0, "8DAV CH1 Diagnosis Information"},
    {0xa000, 1, 4, 16, 0, "8DAV CH2 Diagnosis Information"},
    {0xa000, 1, 5, 16, 0, "8DAV CH3 Diagnosis Information"},
    {0xa000, 1, 6, 16, 0, "8DAV CH4 Diagnosis Information"},
    {0xa000, 1, 7, 16, 0, "8DAV CH5 Diagnosis Information"},
    {0xa000, 1, 8, 16, 0, "8DAV CH6 Diagnosis Information"},
    {0xa000, 1, 9, 16, 0, "8DAV CH7 Diagnosis Information"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__8dav_rx_entries[] = {
    {0x7000, 1, 1, 16, 0, "DA CH0"},
    {0x7000, 1, 2, 16, 0, "DA CH1"},
    {0x7000, 1, 3, 16, 0, "DA CH2"},
    {0x7000, 1, 4, 16, 0, "DA CH3"},
    {0x7000, 1, 5, 16, 0, "DA CH4"},
    {0x7000, 1, 6, 16, 0, "DA CH5"},
    {0x7000, 1, 7, 16, 0, "DA CH6"},
    {0x7000, 1, 8, 16, 0, "DA CH7"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__8dai_tx_entries[] = {
    {0xa000, 1, 1, 16, 0, "8DAI Module Diagnosis Information"},
    {0xa000, 1, 2, 16, 0, "8DAI CH0 Diagnosis Information"},
    {0xa000, 1, 3, 16, 0, "8DAI CH1 Diagnosis Information"},
    {0xa000, 1, 4, 16, 0, "8DAI CH2 Diagnosis Information"},
    {0xa000, 1, 5, 16, 0, "8DAI CH3 Diagnosis Information"},
    {0xa000, 1, 6, 16, 0, "8DAI CH4 Diagnosis Information"},
    {0xa000, 1, 7, 16, 0, "8DAI CH5 Diagnosis Information"},
    {0xa000, 1, 8, 16, 0, "8DAI CH6 Diagnosis Information"},
    {0xa000, 1, 9, 16, 0, "8DAI CH7 Diagnosis Information"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__8dai_rx_entries[] = {
    {0x7000, 1, 1, 16, 0, "DA CH0"},
    {0x7000, 1, 2, 16, 0, "DA CH1"},
    {0x7000, 1, 3, 16, 0, "DA CH2"},
    {0x7000, 1, 4, 16, 0, "DA CH3"},
    {0x7000, 1, 5, 16, 0, "DA CH4"},
    {0x7000, 1, 6, 16, 0, "DA CH5"},
    {0x7000, 1, 7, 16, 0, "DA CH6"},
    {0x7000, 1, 8, 16, 0, "DA CH7"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__4da_tx_entries[] = {
    {0xa000, 1, 1, 16, 0, "DA Module Diagnosis Information"},
    {0xa000, 1, 2, 16, 0, "DA CH0 Diagnosis Information"},
    {0xa000, 1, 3, 16, 0, "DA CH1 Diagnosis Information"},
    {0xa000, 1, 4, 16, 0, "DA CH2 Diagnosis Information"},
    {0xa000, 1, 5, 16, 0, "DA CH3 Diagnosis Information"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__4da_rx_entries[] = {
    {0x7000, 1, 1, 16, 0, "DA CH0"},
    {0x7000, 1, 2, 16, 0, "DA CH1"},
    {0x7000, 1, 3, 16, 0, "DA CH2"},
    {0x7000, 1, 4, 16, 0, "DA CH3"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__4pt_tx_entries[] = {
    {0x6000, 1, 1, 32, 0, "4PT CH0"},
    {0x6000, 1, 2, 32, 0, "4PT CH1"},
    {0x6000, 1, 3, 32, 0, "4PT CH2"},
    {0x6000, 1, 4, 32, 0, "4PT CH3"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__4pt_iso_tx_entries[] = {
    {0x6000, 1, 1, 32, 0, "4PT-ISO CH0"},
    {0x6000, 1, 2, 32, 0, "4PT-ISO CH1"},
    {0x6000, 1, 3, 32, 0, "4PT-ISO CH2"},
    {0x6000, 1, 4, 32, 0, "4PT-ISO CH3"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__4pt_iso_rx_entries[] = {
    {0x7000, 1, 1, 16, 0, "4PT-ISO Control Word"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__4tc_tx_entries[] = {
    {0x6000, 1, 1, 32, 0, "4TC CH0"},
    {0x6000, 1, 2, 32, 0, "4TC CH1"},
    {0x6000, 1, 3, 32, 0, "4TC CH2"},
    {0x6000, 1, 4, 32, 0, "4TC CH3"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__4tc_iso_tx_entries[] = {
    {0x6000, 1, 1, 32, 0, "4TC-ISO CH0"},
    {0x6000, 1, 2, 32, 0, "4TC-ISO CH1"},
    {0x6000, 1, 3, 32, 0, "4TC-ISO CH2"},
    {0x6000, 1, 4, 32, 0, "4TC-ISO CH3"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__4tc_iso_rx_entries[] = {
    {0x7000, 1, 1, 16, 0, "4TC-ISO Control Word"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__4lc_pid_tx_entries[] = {
    {0x6000, 1, 1, 32, 0, "CH0 Temperature"},
    {0x6000, 1, 2, 16, 0, "CH0 OutPercent"},
    {0x6000, 1, 3, 16, 0, "CH0 CoolPercent"},
    {0x6000, 1, 4, 16, 0, "CH0 Kp_AT"},
    {0x6000, 1, 5, 16, 0, "CH0 Ti_AT"},
    {0x6000, 1, 6, 16, 0, "CH0 Td_AT"},
    {0x6000, 1, 7, 16, 0, "CH0 KpCool_AT"},
    {0x6000, 1, 8, 16, 0, "CH0 TiCool_AT"},
    {0x6000, 1, 9, 16, 0, "CH0 TdCool_AT"},
    {0x6000, 1, 10, 16, 0, "CH0 CoolCoefficient_AT"},
    {0x6000, 1, 11, 8, 0, "CH0 Run State"},
    {0x6000, 1, 12, 8, 0, "CH0 ErrorID"},
    {0x6000, 1, 13, 8, 0, "CH0 Output State"},
    {0x6000, 1, 14, 8, 1, "CH0 Reserved"},
    {0x6000, 1, 15, 16, 0, "CH0 ECMaxOut_AT"},
    {0x6001, 1, 1, 32, 0, "CH1 Temperature"},
    {0x6001, 1, 2, 16, 0, "CH1 OutPercent"},
    {0x6001, 1, 3, 16, 0, "CH1 CoolPercent"},
    {0x6001, 1, 4, 16, 0, "CH1 Kp_AT"},
    {0x6001, 1, 5, 16, 0, "CH1 Ti_AT"},
    {0x6001, 1, 6, 16, 0, "CH1 Td_AT"},
    {0x6001, 1, 7, 16, 0, "CH1 KpCool_AT"},
    {0x6001, 1, 8, 16, 0, "CH1 TiCool_AT"},
    {0x6001, 1, 9, 16, 0, "CH1 TdCool_AT"},
    {0x6001, 1, 10, 16, 0, "CH1 CoolCoefficient_AT"},
    {0x6001, 1, 11, 8, 0, "CH1 Run State"},
    {0x6001, 1, 12, 8, 0, "CH1 ErrorID"},
    {0x6001, 1, 13, 8, 0, "CH1 Output State"},
    {0x6001, 1, 14, 8, 1, "CH1 Reserved"},
    {0x6001, 1, 15, 16, 0, "CH1 ECMaxOut_AT"},
    {0x6002, 1, 1, 32, 0, "CH2 Temperature"},
    {0x6002, 1, 2, 16, 0, "CH2 OutPercent"},
    {0x6002, 1, 3, 16, 0, "CH2 CoolPercent"},
    {0x6002, 1, 4, 16, 0, "CH2 Kp_AT"},
    {0x6002, 1, 5, 16, 0, "CH2 Ti_AT"},
    {0x6002, 1, 6, 16, 0, "CH2 Td_AT"},
    {0x6002, 1, 7, 16, 0, "CH2 KpCool_AT"},
    {0x6002, 1, 8, 16, 0, "CH2 TiCool_AT"},
    {0x6002, 1, 9, 16, 0, "CH2 TdCool_AT"},
    {0x6002, 1, 10, 16, 0, "CH2 CoolCoefficient_AT"},
    {0x6002, 1, 11, 8, 0, "CH2 Run State"},
    {0x6002, 1, 12, 8, 0, "CH2 ErrorID"},
    {0x6002, 1, 13, 8, 0, "CH2 Output State"},
    {0x6002, 1, 14, 8, 1, "CH2 Reserved"},
    {0x6002, 1, 15, 16, 0, "CH2 ECMaxOut_AT"},
    {0x6003, 1, 1, 32, 0, "CH3 Temperature"},
    {0x6003, 1, 2, 16, 0, "CH3 OutPercent"},
    {0x6003, 1, 3, 16, 0, "CH3 CoolPercent"},
    {0x6003, 1, 4, 16, 0, "CH3 Kp_AT"},
    {0x6003, 1, 5, 16, 0, "CH3 Ti_AT"},
    {0x6003, 1, 6, 16, 0, "CH3 Td_AT"},
    {0x6003, 1, 7, 16, 0, "CH3 KpCool_AT"},
    {0x6003, 1, 8, 16, 0, "CH3 TiCool_AT"},
    {0x6003, 1, 9, 16, 0, "CH3 TdCool_AT"},
    {0x6003, 1, 10, 16, 0, "CH3 CoolCoefficient_AT"},
    {0x6003, 1, 11, 8, 0, "CH3 Run State"},
    {0x6003, 1, 12, 8, 0, "CH3 ErrorID"},
    {0x6003, 1, 13, 8, 0, "CH3 Output State"},
    {0x6003, 1, 14, 8, 1, "CH3 Reserved"},
    {0x6003, 1, 15, 16, 0, "CH3 ECMaxOut_AT"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__4lc_pid_rx_entries[] = {
    {0x7000, 1, 1, 32, 0, "4LC CH0 Set Point"},
    {0x7000, 1, 2, 16, 0, "4LC CH0 ManualValue"},
    {0x7000, 1, 3, 16, 0, "4LC CH0 Kp"},
    {0x7000, 1, 4, 16, 0, "4LC CH0 Ti"},
    {0x7000, 1, 5, 16, 0, "4LC CH0 Td"},
    {0x7000, 1, 6, 16, 0, "4LC CH0 KpCool"},
    {0x7000, 1, 7, 16, 0, "4LC CH0 TiCool"},
    {0x7000, 1, 8, 16, 0, "4LC CH0 TdCool"},
    {0x7000, 1, 9, 16, 0, "4LC CH0 CoolCoefficient"},
    {0x7000, 1, 10, 8, 0, "4LC CH0 ATCoefficient"},
    {0x7000, 1, 11, 8, 0, "4LC CH0 TempCommand"},
    {0x7000, 1, 12, 16, 0, "4LC CH0 OutputOffset"},
    {0x7000, 1, 13, 16, 0, "4LC CH0 OutputOffsetCool"},
    {0x7000, 1, 14, 16, 0, "4LC CH0 ECMax"},
    {0x7001, 1, 1, 32, 0, "4LC CH1 Set Point"},
    {0x7001, 1, 2, 16, 0, "4LC CH1 ManualValue"},
    {0x7001, 1, 3, 16, 0, "4LC CH1 Kp"},
    {0x7001, 1, 4, 16, 0, "4LC CH1 Ti"},
    {0x7001, 1, 5, 16, 0, "4LC CH1 Td"},
    {0x7001, 1, 6, 16, 0, "4LC CH1 KpCool"},
    {0x7001, 1, 7, 16, 0, "4LC CH1 TiCool"},
    {0x7001, 1, 8, 16, 0, "4LC CH1 TdCool"},
    {0x7001, 1, 9, 16, 0, "4LC CH1 CoolCoefficient"},
    {0x7001, 1, 10, 8, 0, "4LC CH1 ATCoefficient"},
    {0x7001, 1, 11, 8, 0, "4LC CH1 TempCommand"},
    {0x7001, 1, 12, 16, 0, "4LC CH1 OutputOffset"},
    {0x7001, 1, 13, 16, 0, "4LC CH1 OutputOffsetCool"},
    {0x7001, 1, 14, 16, 0, "4LC CH1 ECMax"},
    {0x7002, 1, 1, 32, 0, "4LC CH2 Set Point"},
    {0x7002, 1, 2, 16, 0, "4LC CH2 ManualValue"},
    {0x7002, 1, 3, 16, 0, "4LC CH2 Kp"},
    {0x7002, 1, 4, 16, 0, "4LC CH2 Ti"},
    {0x7002, 1, 5, 16, 0, "4LC CH2 Td"},
    {0x7002, 1, 6, 16, 0, "4LC CH2 KpCool"},
    {0x7002, 1, 7, 16, 0, "4LC CH2 TiCool"},
    {0x7002, 1, 8, 16, 0, "4LC CH2 TdCool"},
    {0x7002, 1, 9, 16, 0, "4LC CH2 CoolCoefficient"},
    {0x7002, 1, 10, 8, 0, "4LC CH2 ATCoefficient"},
    {0x7002, 1, 11, 8, 0, "4LC CH2 TempCommand"},
    {0x7002, 1, 12, 16, 0, "4LC CH2 OutputOffset"},
    {0x7002, 1, 13, 16, 0, "4LC CH2 OutputOffsetCool"},
    {0x7002, 1, 14, 16, 0, "4LC CH2 ECMax"},
    {0x7003, 1, 1, 32, 0, "4LC CH3 Set Point"},
    {0x7003, 1, 2, 16, 0, "4LC CH3 ManualValue"},
    {0x7003, 1, 3, 16, 0, "4LC CH3 Kp"},
    {0x7003, 1, 4, 16, 0, "4LC CH3 Ti"},
    {0x7003, 1, 5, 16, 0, "4LC CH3 Td"},
    {0x7003, 1, 6, 16, 0, "4LC CH3 KpCool"},
    {0x7003, 1, 7, 16, 0, "4LC CH3 TiCool"},
    {0x7003, 1, 8, 16, 0, "4LC CH3 TdCool"},
    {0x7003, 1, 9, 16, 0, "4LC CH3 CoolCoefficient"},
    {0x7003, 1, 10, 8, 0, "4LC CH3 ATCoefficient"},
    {0x7003, 1, 11, 8, 0, "4LC CH3 TempCommand"},
    {0x7003, 1, 12, 16, 0, "4LC CH3 OutputOffset"},
    {0x7003, 1, 13, 16, 0, "4LC CH3 OutputOffsetCool"},
    {0x7003, 1, 14, 16, 0, "4LC CH3 ECMax"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__8tc_pid_tx_entries[] = {
    {0x6000, 1, 1, 32, 0, "8TC-PID CH0 Temperature"},
    {0x6000, 1, 2, 16, 0, "8TC-PID CH0 HeatPercent"},
    {0x6000, 1, 3, 16, 0, "8TC-PID CH0 CoolPercent"},
    {0x6000, 1, 4, 16, 0, "8TC-PID CH0 Kp_AT"},
    {0x6000, 1, 5, 16, 0, "8TC-PID CH0 Ti_AT"},
    {0x6000, 1, 6, 16, 0, "8TC-PID CH0 Td_AT"},
    {0x6000, 1, 7, 16, 0, "8TC-PID CH0 KpCool_AT"},
    {0x6000, 1, 8, 16, 0, "8TC-PID CH0 TiCool_AT"},
    {0x6000, 1, 9, 16, 0, "8TC-PID CH0 TdCool_AT"},
    {0x6000, 1, 10, 16, 0, "8TC-PID CH0 CoolCoefficient_AT"},
    {0x6000, 1, 11, 8, 0, "8TC-PID CH0 Run State"},
    {0x6000, 1, 12, 8, 0, "8TC-PID CH0 ErrorID"},
    {0x6000, 1, 13, 8, 0, "8TC-PID CH0 Output State"},
    {0x6000, 1, 14, 8, 1, "8TC-PID CH0 Reserve"},
    {0x6000, 1, 15, 16, 1, "8TC-PID CH0 Reserve1"},
    {0x6001, 1, 1, 32, 0, "8TC-PID CH1 Temperature"},
    {0x6001, 1, 2, 16, 0, "8TC-PID CH1 HeatPercent"},
    {0x6001, 1, 3, 16, 0, "8TC-PID CH1 CoolPercent"},
    {0x6001, 1, 4, 16, 0, "8TC-PID CH1 Kp_AT"},
    {0x6001, 1, 5, 16, 0, "8TC-PID CH1 Ti_AT"},
    {0x6001, 1, 6, 16, 0, "8TC-PID CH1 Td_AT"},
    {0x6001, 1, 7, 16, 0, "8TC-PID CH1 KpCool_AT"},
    {0x6001, 1, 8, 16, 0, "8TC-PID CH1 TiCool_AT"},
    {0x6001, 1, 9, 16, 0, "8TC-PID CH1 TdCool_AT"},
    {0x6001, 1, 10, 16, 0, "8TC-PID CH1 CoolCoefficient_AT"},
    {0x6001, 1, 11, 8, 0, "8TC-PID CH1 Run State"},
    {0x6001, 1, 12, 8, 0, "8TC-PID CH1 ErrorID"},
    {0x6001, 1, 13, 8, 0, "8TC-PID CH1 Output State"},
    {0x6001, 1, 14, 8, 1, "8TC-PID CH1 Reserve"},
    {0x6001, 1, 15, 16, 1, "8TC-PID CH1 Reserve1"},
    {0x6002, 1, 1, 32, 0, "8TC-PID CH2 Temperature"},
    {0x6002, 1, 2, 16, 0, "8TC-PID CH2 HeatPercent"},
    {0x6002, 1, 3, 16, 0, "8TC-PID CH2 CoolPercent"},
    {0x6002, 1, 4, 16, 0, "8TC-PID CH2 Kp_AT"},
    {0x6002, 1, 5, 16, 0, "8TC-PID CH2 Ti_AT"},
    {0x6002, 1, 6, 16, 0, "8TC-PID CH2 Td_AT"},
    {0x6002, 1, 7, 16, 0, "8TC-PID CH2 KpCool_AT"},
    {0x6002, 1, 8, 16, 0, "8TC-PID CH2 TiCool_AT"},
    {0x6002, 1, 9, 16, 0, "8TC-PID CH2 TdCool_AT"},
    {0x6002, 1, 10, 16, 0, "8TC-PID CH2 CoolCoefficient_AT"},
    {0x6002, 1, 11, 8, 0, "8TC-PID CH2 Run State"},
    {0x6002, 1, 12, 8, 0, "8TC-PID CH2 ErrorID"},
    {0x6002, 1, 13, 8, 0, "8TC-PID CH2 Output State"},
    {0x6002, 1, 14, 8, 1, "8TC-PID CH2 Reserve"},
    {0x6002, 1, 15, 16, 1, "8TC-PID CH2 Reserve1"},
    {0x6003, 1, 1, 32, 0, "8TC-PID CH3 Temperature"},
    {0x6003, 1, 2, 16, 0, "8TC-PID CH3 HeatPercent"},
    {0x6003, 1, 3, 16, 0, "8TC-PID CH3 CoolPercent"},
    {0x6003, 1, 4, 16, 0, "8TC-PID CH3 Kp_AT"},
    {0x6003, 1, 5, 16, 0, "8TC-PID CH3 Ti_AT"},
    {0x6003, 1, 6, 16, 0, "8TC-PID CH3 Td_AT"},
    {0x6003, 1, 7, 16, 0, "8TC-PID CH3 KpCool_AT"},
    {0x6003, 1, 8, 16, 0, "8TC-PID CH3 TiCool_AT"},
    {0x6003, 1, 9, 16, 0, "8TC-PID CH3 TdCool_AT"},
    {0x6003, 1, 10, 16, 0, "8TC-PID CH3 CoolCoefficient_AT"},
    {0x6003, 1, 11, 8, 0, "8TC-PID CH3 Run State"},
    {0x6003, 1, 12, 8, 0, "8TC-PID CH3 ErrorID"},
    {0x6003, 1, 13, 8, 0, "8TC-PID CH3 Output State"},
    {0x6003, 1, 14, 8, 1, "8TC-PID CH3 Reserve"},
    {0x6003, 1, 15, 16, 1, "8TC-PID CH3 Reserve1"},
    {0x6004, 1, 1, 32, 0, "8TC-PID CH4 Temperature"},
    {0x6004, 1, 2, 16, 0, "8TC-PID CH4 HeatPercent"},
    {0x6004, 1, 3, 16, 0, "8TC-PID CH4 CoolPercent"},
    {0x6004, 1, 4, 16, 0, "8TC-PID CH4 Kp_AT"},
    {0x6004, 1, 5, 16, 0, "8TC-PID CH4 Ti_AT"},
    {0x6004, 1, 6, 16, 0, "8TC-PID CH4 Td_AT"},
    {0x6004, 1, 7, 16, 0, "8TC-PID CH4 KpCool_AT"},
    {0x6004, 1, 8, 16, 0, "8TC-PID CH4 TiCool_AT"},
    {0x6004, 1, 9, 16, 0, "8TC-PID CH4 TdCool_AT"},
    {0x6004, 1, 10, 16, 0, "8TC-PID CH4 CoolCoefficient_AT"},
    {0x6004, 1, 11, 8, 0, "8TC-PID CH4 Run State"},
    {0x6004, 1, 12, 8, 0, "8TC-PID CH4 ErrorID"},
    {0x6004, 1, 13, 8, 0, "8TC-PID CH4 Output State"},
    {0x6004, 1, 14, 8, 1, "8TC-PID CH4 Reserve"},
    {0x6004, 1, 15, 16, 1, "8TC-PID CH4 Reserve1"},
    {0x6005, 1, 1, 32, 0, "8TC-PID CH5 Temperature"},
    {0x6005, 1, 2, 16, 0, "8TC-PID CH5 HeatPercent"},
    {0x6005, 1, 3, 16, 0, "8TC-PID CH5 CoolPercent"},
    {0x6005, 1, 4, 16, 0, "8TC-PID CH5 Kp_AT"},
    {0x6005, 1, 5, 16, 0, "8TC-PID CH5 Ti_AT"},
    {0x6005, 1, 6, 16, 0, "8TC-PID CH5 Td_AT"},
    {0x6005, 1, 7, 16, 0, "8TC-PID CH5 KpCool_AT"},
    {0x6005, 1, 8, 16, 0, "8TC-PID CH5 TiCool_AT"},
    {0x6005, 1, 9, 16, 0, "8TC-PID CH5 TdCool_AT"},
    {0x6005, 1, 10, 16, 0, "8TC-PID CH5 CoolCoefficient_AT"},
    {0x6005, 1, 11, 8, 0, "8TC-PID CH5 Run State"},
    {0x6005, 1, 12, 8, 0, "8TC-PID CH5 ErrorID"},
    {0x6005, 1, 13, 8, 0, "8TC-PID CH5 Output State"},
    {0x6005, 1, 14, 8, 1, "8TC-PID CH5 Reserve"},
    {0x6005, 1, 15, 16, 1, "8TC-PID CH5 Reserve1"},
    {0x6006, 1, 1, 32, 0, "8TC-PID CH6 Temperature"},
    {0x6006, 1, 2, 16, 0, "8TC-PID CH6 HeatPercent"},
    {0x6006, 1, 3, 16, 0, "8TC-PID CH6 CoolPercent"},
    {0x6006, 1, 4, 16, 0, "8TC-PID CH6 Kp_AT"},
    {0x6006, 1, 5, 16, 0, "8TC-PID CH6 Ti_AT"},
    {0x6006, 1, 6, 16, 0, "8TC-PID CH6 Td_AT"},
    {0x6006, 1, 7, 16, 0, "8TC-PID CH6 KpCool_AT"},
    {0x6006, 1, 8, 16, 0, "8TC-PID CH6 TiCool_AT"},
    {0x6006, 1, 9, 16, 0, "8TC-PID CH6 TdCool_AT"},
    {0x6006, 1, 10, 16, 0, "8TC-PID CH6 CoolCoefficient_AT"},
    {0x6006, 1, 11, 8, 0, "8TC-PID CH6 Run State"},
    {0x6006, 1, 12, 8, 0, "8TC-PID CH6 ErrorID"},
    {0x6006, 1, 13, 8, 0, "8TC-PID CH6 Output State"},
    {0x6006, 1, 14, 8, 1, "8TC-PID CH6 Reserve"},
    {0x6006, 1, 15, 16, 1, "8TC-PID CH6 Reserve1"},
    {0x6007, 1, 1, 32, 0, "8TC-PID CH7 Temperature"},
    {0x6007, 1, 2, 16, 0, "8TC-PID CH7 HeatPercent"},
    {0x6007, 1, 3, 16, 0, "8TC-PID CH7 CoolPercent"},
    {0x6007, 1, 4, 16, 0, "8TC-PID CH7 Kp_AT"},
    {0x6007, 1, 5, 16, 0, "8TC-PID CH7 Ti_AT"},
    {0x6007, 1, 6, 16, 0, "8TC-PID CH7 Td_AT"},
    {0x6007, 1, 7, 16, 0, "8TC-PID CH7 KpCool_AT"},
    {0x6007, 1, 8, 16, 0, "8TC-PID CH7 TiCool_AT"},
    {0x6007, 1, 9, 16, 0, "8TC-PID CH7 TdCool_AT"},
    {0x6007, 1, 10, 16, 0, "8TC-PID CH7 CoolCoefficient_AT"},
    {0x6007, 1, 11, 8, 0, "8TC-PID CH7 Run State"},
    {0x6007, 1, 12, 8, 0, "8TC-PID CH7 ErrorID"},
    {0x6007, 1, 13, 8, 0, "8TC-PID CH7 Output State"},
    {0x6007, 1, 14, 8, 1, "8TC-PID CH7 Reserve"},
    {0x6007, 1, 15, 16, 1, "8TC-PID CH7 Reserve1"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__8tc_pid_rx_entries[] = {
    {0x7000, 1, 1, 32, 0, "8TC-PID CH0 Set Point"},
    {0x7000, 1, 2, 16, 0, "8TC-PID CH0 ManualValue"},
    {0x7000, 1, 3, 16, 0, "8TC-PID CH0 KP"},
    {0x7000, 1, 4, 16, 0, "8TC-PID CH0 TI"},
    {0x7000, 1, 5, 16, 0, "8TC-PID CH0 Td"},
    {0x7000, 1, 6, 16, 0, "8TC-PID CH0 KpCool"},
    {0x7000, 1, 7, 16, 0, "8TC-PID CH0 TiCool"},
    {0x7000, 1, 8, 16, 0, "8TC-PID CH0 TdCool"},
    {0x7000, 1, 9, 16, 0, "8TC-PID CH0 CoolCoefficient"},
    {0x7000, 1, 10, 8, 0, "8TC-PID CH0 ATCoefficient"},
    {0x7000, 1, 11, 8, 0, "8TC-PID CH0 TempCommand"},
    {0x7000, 1, 12, 16, 1, "8TC-PID CH0 Reserve"},
    {0x7001, 1, 1, 32, 0, "8TC-PID CH1 Set Point"},
    {0x7001, 1, 2, 16, 0, "8TC-PID CH1 ManualValue"},
    {0x7001, 1, 3, 16, 0, "8TC-PID CH1 KP"},
    {0x7001, 1, 4, 16, 0, "8TC-PID CH1 TI"},
    {0x7001, 1, 5, 16, 0, "8TC-PID CH1 Td"},
    {0x7001, 1, 6, 16, 0, "8TC-PID CH1 KpCool"},
    {0x7001, 1, 7, 16, 0, "8TC-PID CH1 TiCool"},
    {0x7001, 1, 8, 16, 0, "8TC-PID CH1 TdCool"},
    {0x7001, 1, 9, 16, 0, "8TC-PID CH1 CoolCoefficient"},
    {0x7001, 1, 10, 8, 0, "8TC-PID CH1 ATCoefficient"},
    {0x7001, 1, 11, 8, 0, "8TC-PID CH1 TempCommand"},
    {0x7001, 1, 12, 16, 1, "8TC-PID CH1 Reserve"},
    {0x7002, 1, 1, 32, 0, "8TC-PID CH2 Set Point"},
    {0x7002, 1, 2, 16, 0, "8TC-PID CH2 ManualValue"},
    {0x7002, 1, 3, 16, 0, "8TC-PID CH2 KP"},
    {0x7002, 1, 4, 16, 0, "8TC-PID CH2 TI"},
    {0x7002, 1, 5, 16, 0, "8TC-PID CH2 Td"},
    {0x7002, 1, 6, 16, 0, "8TC-PID CH2 KpCool"},
    {0x7002, 1, 7, 16, 0, "8TC-PID CH2 TiCool"},
    {0x7002, 1, 8, 16, 0, "8TC-PID CH2 TdCool"},
    {0x7002, 1, 9, 16, 0, "8TC-PID CH2 CoolCoefficient"},
    {0x7002, 1, 10, 8, 0, "8TC-PID CH2 ATCoefficient"},
    {0x7002, 1, 11, 8, 0, "8TC-PID CH2 TempCommand"},
    {0x7002, 1, 12, 16, 1, "8TC-PID CH2 Reserve"},
    {0x7003, 1, 1, 32, 0, "8TC-PID CH3 Set Point"},
    {0x7003, 1, 2, 16, 0, "8TC-PID CH3 ManualValue"},
    {0x7003, 1, 3, 16, 0, "8TC-PID CH3 KP"},
    {0x7003, 1, 4, 16, 0, "8TC-PID CH3 TI"},
    {0x7003, 1, 5, 16, 0, "8TC-PID CH3 Td"},
    {0x7003, 1, 6, 16, 0, "8TC-PID CH3 KpCool"},
    {0x7003, 1, 7, 16, 0, "8TC-PID CH3 TiCool"},
    {0x7003, 1, 8, 16, 0, "8TC-PID CH3 TdCool"},
    {0x7003, 1, 9, 16, 0, "8TC-PID CH3 CoolCoefficient"},
    {0x7003, 1, 10, 8, 0, "8TC-PID CH3 ATCoefficient"},
    {0x7003, 1, 11, 8, 0, "8TC-PID CH3 TempCommand"},
    {0x7003, 1, 12, 16, 1, "8TC-PID CH3 Reserve"},
    {0x7004, 1, 1, 32, 0, "8TC-PID CH4 Set Point"},
    {0x7004, 1, 2, 16, 0, "8TC-PID CH4 ManualValue"},
    {0x7004, 1, 3, 16, 0, "8TC-PID CH4 KP"},
    {0x7004, 1, 4, 16, 0, "8TC-PID CH4 TI"},
    {0x7004, 1, 5, 16, 0, "8TC-PID CH4 Td"},
    {0x7004, 1, 6, 16, 0, "8TC-PID CH4 KpCool"},
    {0x7004, 1, 7, 16, 0, "8TC-PID CH4 TiCool"},
    {0x7004, 1, 8, 16, 0, "8TC-PID CH4 TdCool"},
    {0x7004, 1, 9, 16, 0, "8TC-PID CH4 CoolCoefficient"},
    {0x7004, 1, 10, 8, 0, "8TC-PID CH4 ATCoefficient"},
    {0x7004, 1, 11, 8, 0, "8TC-PID CH4 TempCommand"},
    {0x7004, 1, 12, 16, 1, "8TC-PID CH4 Reserve"},
    {0x7005, 1, 1, 32, 0, "8TC-PID CH5 Set Point"},
    {0x7005, 1, 2, 16, 0, "8TC-PID CH5 ManualValue"},
    {0x7005, 1, 3, 16, 0, "8TC-PID CH5 KP"},
    {0x7005, 1, 4, 16, 0, "8TC-PID CH5 TI"},
    {0x7005, 1, 5, 16, 0, "8TC-PID CH5 Td"},
    {0x7005, 1, 6, 16, 0, "8TC-PID CH5 KpCool"},
    {0x7005, 1, 7, 16, 0, "8TC-PID CH5 TiCool"},
    {0x7005, 1, 8, 16, 0, "8TC-PID CH5 TdCool"},
    {0x7005, 1, 9, 16, 0, "8TC-PID CH5 CoolCoefficient"},
    {0x7005, 1, 10, 8, 0, "8TC-PID CH5 ATCoefficient"},
    {0x7005, 1, 11, 8, 0, "8TC-PID CH5 TempCommand"},
    {0x7005, 1, 12, 16, 1, "8TC-PID CH5 Reserve"},
    {0x7006, 1, 1, 32, 0, "8TC-PID CH6 Set Point"},
    {0x7006, 1, 2, 16, 0, "8TC-PID CH6 ManualValue"},
    {0x7006, 1, 3, 16, 0, "8TC-PID CH6 KP"},
    {0x7006, 1, 4, 16, 0, "8TC-PID CH6 TI"},
    {0x7006, 1, 5, 16, 0, "8TC-PID CH6 Td"},
    {0x7006, 1, 6, 16, 0, "8TC-PID CH6 KpCool"},
    {0x7006, 1, 7, 16, 0, "8TC-PID CH6 TiCool"},
    {0x7006, 1, 8, 16, 0, "8TC-PID CH6 TdCool"},
    {0x7006, 1, 9, 16, 0, "8TC-PID CH6 CoolCoefficient"},
    {0x7006, 1, 10, 8, 0, "8TC-PID CH6 ATCoefficient"},
    {0x7006, 1, 11, 8, 0, "8TC-PID CH6 TempCommand"},
    {0x7006, 1, 12, 16, 1, "8TC-PID CH6 Reserve"},
    {0x7007, 1, 1, 32, 0, "8TC-PID CH7 Set Point"},
    {0x7007, 1, 2, 16, 0, "8TC-PID CH7 ManualValue"},
    {0x7007, 1, 3, 16, 0, "8TC-PID CH7 KP"},
    {0x7007, 1, 4, 16, 0, "8TC-PID CH7 TI"},
    {0x7007, 1, 5, 16, 0, "8TC-PID CH7 Td"},
    {0x7007, 1, 6, 16, 0, "8TC-PID CH7 KpCool"},
    {0x7007, 1, 7, 16, 0, "8TC-PID CH7 TiCool"},
    {0x7007, 1, 8, 16, 0, "8TC-PID CH7 TdCool"},
    {0x7007, 1, 9, 16, 0, "8TC-PID CH7 CoolCoefficient"},
    {0x7007, 1, 10, 8, 0, "8TC-PID CH7 ATCoefficient"},
    {0x7007, 1, 11, 8, 0, "8TC-PID CH7 TempCommand"},
    {0x7007, 1, 12, 16, 1, "8TC-PID CH7 Reserve"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__8tc_tx_entries[] = {
    {0x6000, 1, 1, 32, 0, "8TC CH0 Temperature"},
    {0x6000, 1, 2, 32, 0, "8TC CH1 Temperature"},
    {0x6000, 1, 3, 32, 0, "8TC CH2 Temperature"},
    {0x6000, 1, 4, 32, 0, "8TC CH3 Temperature"},
    {0x6000, 1, 5, 32, 0, "8TC CH4 Temperature"},
    {0x6000, 1, 6, 32, 0, "8TC CH5 Temperature"},
    {0x6000, 1, 7, 32, 0, "8TC CH6 Temperature"},
    {0x6000, 1, 8, 32, 0, "8TC CH7 Temperature"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_gl20s__ps2_tx_entries[] = {
    {0xa000, 1, 1, 16, 0, "PS2 Module Diagnosis Information"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_2can_tx_entries[] = {
    {0x6000, 1, 1, 32, 0, "CAN0_Frame0_RX_ID"},
    {0x6000, 1, 2, 32, 0, "CAN0_Frame0_RXDATA0"},
    {0x6000, 1, 3, 32, 0, "CAN0_Frame0_RXDATA1"},
    {0x6000, 1, 4, 32, 0, "CAN0_Frame1_RX_ID"},
    {0x6000, 1, 5, 32, 0, "CAN0_Frame1_RXDATA0"},
    {0x6000, 1, 6, 32, 0, "CAN0_Frame1_RXDATA1"},
    {0x6000, 1, 7, 32, 0, "CAN0_Frame2_RX_ID"},
    {0x6000, 1, 8, 32, 0, "CAN0_Frame2_RXDATA0"},
    {0x6000, 1, 9, 32, 0, "CAN0_Frame2_RXDATA1"},
    {0x6000, 1, 10, 32, 0, "CAN0_Frame3_RX_ID"},
    {0x6000, 1, 11, 32, 0, "CAN0_Frame3_RXDATA0"},
    {0x6000, 1, 12, 32, 0, "CAN0_Frame3_RXDATA1"},
    {0x6000, 1, 13, 32, 0, "CAN0_Frame4_RX_ID"},
    {0x6000, 1, 14, 32, 0, "CAN0_Frame4_RXDATA0"},
    {0x6000, 1, 15, 32, 0, "CAN0_Frame4_RXDATA1"},
    {0x6000, 1, 16, 32, 0, "CAN0_Frame5_RX_ID"},
    {0x6000, 1, 17, 32, 0, "CAN0_Frame5_RXDATA0"},
    {0x6000, 1, 18, 32, 0, "CAN0_Frame5_RXDATA1"},
    {0x6000, 1, 19, 32, 0, "CAN0_Frame6_RX_ID"},
    {0x6000, 1, 20, 32, 0, "CAN0_Frame6_RXDATA0"},
    {0x6000, 1, 21, 32, 0, "CAN0_Frame6_RXDATA1"},
    {0x6000, 1, 22, 32, 0, "CAN0_Frame7_RX_ID"},
    {0x6000, 1, 23, 32, 0, "CAN0_Frame7_RXDATA0"},
    {0x6000, 1, 24, 32, 0, "CAN0_Frame7_RXDATA1"},
    {0x6000, 1, 25, 32, 0, "CAN0_Frame8_RX_ID"},
    {0x6000, 1, 26, 32, 0, "CAN0_Frame8_RXDATA0"},
    {0x6000, 1, 27, 32, 0, "CAN0_Frame8_RXDATA1"},
    {0x6000, 1, 28, 32, 0, "CAN0_Frame0_TO_Frame3_length"},
    {0x6000, 1, 29, 32, 0, "CAN0_Frame4_TO_Frame7_length"},
    {0x6000, 1, 30, 32, 0, "CAN0_RX_Couter and Frame8_length"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_2can_rx_entries[] = {
    {0x7000, 1, 1, 32, 0, "CAN0_Frame0_TX_ID"},
    {0x7000, 1, 2, 32, 0, "CAN0_Frame0_TXDATA0"},
    {0x7000, 1, 3, 32, 0, "CAN0_Frame0_TXDATA1"},
    {0x7000, 1, 4, 32, 0, "CAN0_Frame1_TX_ID"},
    {0x7000, 1, 5, 32, 0, "CAN0_Frame1_TXDATA0"},
    {0x7000, 1, 6, 32, 0, "CAN0_Frame1_TXDATA1"},
    {0x7000, 1, 7, 32, 0, "CAN0_Frame2_TX_ID"},
    {0x7000, 1, 8, 32, 0, "CAN0_Frame2_TXDATA0"},
    {0x7000, 1, 9, 32, 0, "CAN0_Frame2_TXDATA1"},
    {0x7000, 1, 10, 32, 0, "CAN0_Frame3_TX_ID"},
    {0x7000, 1, 11, 32, 0, "CAN0_Frame3_TXDATA0"},
    {0x7000, 1, 12, 32, 0, "CAN0_Frame3_TXDATA1"},
    {0x7000, 1, 13, 32, 0, "CAN0_Frame4_TX_ID"},
    {0x7000, 1, 14, 32, 0, "CAN0_Frame4_TXDATA0"},
    {0x7000, 1, 15, 32, 0, "CAN0_Frame4_TXDATA1"},
    {0x7000, 1, 16, 32, 0, "CAN0_Frame5_TX_ID"},
    {0x7000, 1, 17, 32, 0, "CAN0_Frame5_TXDATA0"},
    {0x7000, 1, 18, 32, 0, "CAN0_Frame5_TXDATA1"},
    {0x7000, 1, 19, 32, 0, "CAN0_Frame6_TX_ID"},
    {0x7000, 1, 20, 32, 0, "CAN0_Frame6_TXDATA0"},
    {0x7000, 1, 21, 32, 0, "CAN0_Frame6_TXDATA1"},
    {0x7000, 1, 22, 32, 0, "CAN0_Frame7_TX_ID"},
    {0x7000, 1, 23, 32, 0, "CAN0_Frame7_TXDATA0"},
    {0x7000, 1, 24, 32, 0, "CAN0_Frame7_TXDATA1"},
    {0x7000, 1, 25, 32, 0, "CAN0_Frame8_TX_ID"},
    {0x7000, 1, 26, 32, 0, "CAN0_Frame8_TXDATA0"},
    {0x7000, 1, 27, 32, 0, "CAN0_Frame8_TXDATA1"},
    {0x7000, 1, 28, 32, 0, "CAN0_Frame0_TO_Frame3_length"},
    {0x7000, 1, 29, 32, 0, "CAN0_Frame4_TO_Frame7_length"},
    {0x7000, 1, 30, 32, 0, "CAN0_TX_Couter and Frame8_length"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_2s485_tx_entries[] = {
    {0x6000, 1, 1, 32, 0, "RS485-0 RXCOUNTER and length"},
    {0x6000, 1, 2, 32, 0, "RS485-0 RX_DATA1"},
    {0x6000, 1, 3, 32, 0, "RS485-0 RX_DATA2"},
    {0x6000, 1, 4, 32, 0, "RS485-0 RX_DATA3"},
    {0x6000, 1, 5, 32, 0, "RS485-0 RX_DATA4"},
    {0x6000, 1, 6, 32, 0, "RS485-0 RX_DATA5"},
    {0x6000, 1, 7, 32, 0, "RS485-0 RX_DATA6"},
    {0x6000, 1, 8, 32, 0, "RS485-1 RXCOUNTER and length"},
    {0x6000, 1, 9, 32, 0, "RS485-1 RX_DATA1"},
    {0x6000, 1, 10, 32, 0, "RS485-1 RX_DATA2"},
    {0x6000, 1, 11, 32, 0, "RS485-1 RX_DATA3"},
    {0x6000, 1, 12, 32, 0, "RS485-1 RX_DATA4"},
    {0x6000, 1, 13, 32, 0, "RS485-1 RX_DATA5"},
    {0x6000, 1, 14, 32, 0, "RS485-1 RX_DATA6"},
    {0x6000, 1, 15, 32, 0, "RX_status"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_2s485_rx_entries[] = {
    {0x7000, 1, 1, 32, 0, "RS485-0 TXCOUNTER and length"},
    {0x7000, 1, 2, 32, 0, "RS485-0 TX_DATA1"},
    {0x7000, 1, 3, 32, 0, "RS485-0 TX_DATA2"},
    {0x7000, 1, 4, 32, 0, "RS485-0 TX_DATA3"},
    {0x7000, 1, 5, 32, 0, "RS485-0 TX_DATA4"},
    {0x7000, 1, 6, 32, 0, "RS485-0 TX_DATA5"},
    {0x7000, 1, 7, 32, 0, "RS485-0 TX_DATA6"},
    {0x7000, 1, 8, 32, 0, "RS485-1 TXCOUNTER and length"},
    {0x7000, 1, 9, 32, 0, "RS485-1 TX_DATA1"},
    {0x7000, 1, 10, 32, 0, "RS485-1 TX_DATA2"},
    {0x7000, 1, 11, 32, 0, "RS485-1 TX_DATA3"},
    {0x7000, 1, 12, 32, 0, "RS485-1 TX_DATA4"},
    {0x7000, 1, 13, 32, 0, "RS485-1 TX_DATA5"},
    {0x7000, 1, 14, 32, 0, "RS485-1 TX_DATA6"},
    {0x7000, 1, 15, 32, 0, "TX_status"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_2scom_tx_entries[] = {
    {0x6000, 1, 1, 32, 0, "2SCOM-1 RXCOUNTER and length"},
    {0x6000, 1, 2, 32, 0, "2SCOM-1 RX_DATA1"},
    {0x6000, 1, 3, 32, 0, "2SCOM-1 RX_DATA2"},
    {0x6000, 1, 4, 32, 0, "2SCOM-1 RX_DATA3"},
    {0x6000, 1, 5, 32, 0, "2SCOM-1 RX_DATA4"},
    {0x6000, 1, 6, 32, 0, "2SCOM-1 RX_DATA5"},
    {0x6000, 1, 7, 32, 0, "2SCOM-1 RX_DATA6"},
    {0x6000, 1, 8, 32, 0, "2SCOM-2 RXCOUNTER and length"},
    {0x6000, 1, 9, 32, 0, "2SCOM-2 RX_DATA1"},
    {0x6000, 1, 10, 32, 0, "2SCOM-2 RX_DATA2"},
    {0x6000, 1, 11, 32, 0, "2SCOM-2 RX_DATA3"},
    {0x6000, 1, 12, 32, 0, "2SCOM-2 RX_DATA4"},
    {0x6000, 1, 13, 32, 0, "2SCOM-2 RX_DATA5"},
    {0x6000, 1, 14, 32, 0, "2SCOM-2 RX_DATA6"},
    {0x6000, 1, 15, 32, 0, "RX_status"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_2scom_rx_entries[] = {
    {0x7000, 1, 1, 32, 0, "2SCOM-1 TXCOUNTER and length"},
    {0x7000, 1, 2, 32, 0, "2SCOM-1 TX_DATA1"},
    {0x7000, 1, 3, 32, 0, "2SCOM-1 TX_DATA2"},
    {0x7000, 1, 4, 32, 0, "2SCOM-1 TX_DATA3"},
    {0x7000, 1, 5, 32, 0, "2SCOM-1 TX_DATA4"},
    {0x7000, 1, 6, 32, 0, "2SCOM-1 TX_DATA5"},
    {0x7000, 1, 7, 32, 0, "2SCOM-1 TX_DATA6"},
    {0x7000, 1, 8, 32, 0, "2SCOM-2 TXCOUNTER and length"},
    {0x7000, 1, 9, 32, 0, "2SCOM-2 TX_DATA1"},
    {0x7000, 1, 10, 32, 0, "2SCOM-2 TX_DATA2"},
    {0x7000, 1, 11, 32, 0, "2SCOM-2 TX_DATA3"},
    {0x7000, 1, 12, 32, 0, "2SCOM-2 TX_DATA4"},
    {0x7000, 1, 13, 32, 0, "2SCOM-2 TX_DATA5"},
    {0x7000, 1, 14, 32, 0, "2SCOM-2 TX_DATA6"},
    {0x7000, 1, 15, 32, 0, "TX_status"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_2ssi_tx_entries[] = {
    {0x6000, 1, 1, 32, 0, "Ch0 Para Input"},
    {0x6000, 1, 2, 32, 1, "Ch0 Reserve data0"},
    {0x6000, 1, 3, 32, 1, "Ch0 Reserve data1"},
    {0x6000, 1, 4, 32, 1, "Ch0 Reserve data2"},
    {0x6000, 1, 5, 32, 1, "Ch0 Reserve data3"},
    {0x6000, 1, 6, 32, 1, "Ch0 Reserve data4"},
    {0x6000, 1, 7, 32, 0, "Ch1 Para Input"},
    {0x6000, 1, 8, 32, 1, "Ch1 Reserve data0"},
    {0x6000, 1, 9, 32, 1, "Ch1 Reserve data1"},
    {0x6000, 1, 10, 32, 1, "Ch1 Reserve data2"},
    {0x6000, 1, 11, 32, 1, "Ch1 Reserve data3"},
    {0x6000, 1, 12, 32, 1, "Ch1 Reserve data4"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_1dnm_tx_entries[] = {
    {0x6000, 1, 1, 32, 0, "TxPDO01"},
    {0x6000, 1, 2, 32, 0, "TxPDO01"},
    {0x6000, 1, 3, 32, 0, "TxPDO02"},
    {0x6000, 1, 4, 32, 0, "TxPDO02"},
    {0x6000, 1, 5, 32, 0, "TxPDO03"},
    {0x6000, 1, 6, 32, 0, "TxPDO03"},
    {0x6000, 1, 7, 32, 0, "TxPDO04"},
    {0x6000, 1, 8, 32, 0, "TxPDO04"},
    {0x6000, 1, 9, 32, 0, "TxPDO05"},
    {0x6000, 1, 10, 32, 0, "TxPDO05"},
    {0x6000, 1, 11, 32, 0, "TxPDO06"},
    {0x6000, 1, 12, 32, 0, "TxPDO06"},
    {0x6000, 1, 13, 32, 0, "TxPDO07"},
    {0x6000, 1, 14, 32, 0, "TxPDO07"},
    {0x6000, 1, 15, 32, 0, "TxPDO08"},
    {0x6000, 1, 16, 32, 0, "TxPDO08"},
    {0x6000, 1, 17, 32, 0, "TxPDO09"},
    {0x6000, 1, 18, 32, 0, "TxPDO09"},
    {0x6000, 1, 19, 32, 0, "TxPDO010"},
    {0x6000, 1, 20, 32, 0, "TxPDO010"},
    {0x6000, 1, 21, 32, 0, "TxPDO11"},
    {0x6000, 1, 22, 32, 0, "TxPDO11"},
    {0x6000, 1, 23, 32, 0, "TxPDO12"},
    {0x6000, 1, 24, 32, 0, "TxPDO12"},
    {0x6000, 1, 25, 32, 0, "TxPDO13"},
    {0x6000, 1, 26, 32, 0, "TxPDO13"},
    {0x6000, 1, 27, 32, 0, "TxPDO14"},
    {0x6000, 1, 28, 32, 0, "TxPDO14"},
    {0x6000, 1, 29, 32, 0, "TxPDO15"},
    {0x6000, 1, 30, 32, 0, "TxPDO15"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_1dnm_rx_entries[] = {
    {0x7000, 1, 1, 32, 0, "RxPDO01"},
    {0x7000, 1, 2, 32, 0, "RxPDO01"},
    {0x7000, 1, 3, 32, 0, "RxPDO02"},
    {0x7000, 1, 4, 32, 0, "RxPDO02"},
    {0x7000, 1, 5, 32, 0, "RxPDO03"},
    {0x7000, 1, 6, 32, 0, "RxPDO03"},
    {0x7000, 1, 7, 32, 0, "RxPDO04"},
    {0x7000, 1, 8, 32, 0, "RxPDO04"},
    {0x7000, 1, 9, 32, 0, "RxPDO05"},
    {0x7000, 1, 10, 32, 0, "RxPDO05"},
    {0x7000, 1, 11, 32, 0, "RxPDO06"},
    {0x7000, 1, 12, 32, 0, "RxPDO06"},
    {0x7000, 1, 13, 32, 0, "RxPDO07"},
    {0x7000, 1, 14, 32, 0, "RxPDO07"},
    {0x7000, 1, 15, 32, 0, "RxPDO08"},
    {0x7000, 1, 16, 32, 0, "RxPDO08"},
    {0x7000, 1, 17, 32, 0, "RxPDO09"},
    {0x7000, 1, 18, 32, 0, "RxPDO09"},
    {0x7000, 1, 19, 32, 0, "RxPDO010"},
    {0x7000, 1, 20, 32, 0, "RxPDO010"},
    {0x7000, 1, 21, 32, 0, "RxPDO011"},
    {0x7000, 1, 22, 32, 0, "RxPDO011"},
    {0x7000, 1, 23, 32, 0, "RxPDO012"},
    {0x7000, 1, 24, 32, 0, "RxPDO012"},
    {0x7000, 1, 25, 32, 0, "RxPDO013"},
    {0x7000, 1, 26, 32, 0, "RxPDO013"},
    {0x7000, 1, 27, 32, 0, "RxPDO014"},
    {0x7000, 1, 28, 32, 0, "RxPDO014"},
    {0x7000, 1, 29, 32, 0, "RxPDO015"},
    {0x7000, 1, 30, 32, 0, "RxPDO015"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_dnslave_tx_entries[] = {
    {0x6000, 1, 1, 32, 0, "TxPDO01"},
    {0x6000, 1, 2, 32, 0, "TxPDO01"},
    {0x6000, 1, 3, 32, 0, "TxPDO02"},
    {0x6000, 1, 4, 32, 0, "TxPDO02"},
    {0x6000, 1, 5, 32, 0, "TxPDO03"},
    {0x6000, 1, 6, 32, 0, "TxPDO03"},
    {0x6000, 1, 7, 32, 0, "TxPDO04"},
    {0x6000, 1, 8, 32, 0, "TxPDO04"},
    {0x6000, 1, 9, 32, 0, "TxPDO05"},
    {0x6000, 1, 10, 32, 0, "TxPDO05"},
    {0x6000, 1, 11, 32, 0, "TxPDO06"},
    {0x6000, 1, 12, 32, 0, "TxPDO06"},
    {0x6000, 1, 13, 32, 0, "TxPDO07"},
    {0x6000, 1, 14, 32, 0, "TxPDO07"},
    {0x6000, 1, 15, 32, 0, "TxPDO08"},
    {0x6000, 1, 16, 32, 0, "TxPDO08"},
    {0x6000, 1, 17, 32, 0, "TxPDO09"},
    {0x6000, 1, 18, 32, 0, "TxPDO09"},
    {0x6000, 1, 19, 32, 0, "TxPDO10"},
    {0x6000, 1, 20, 32, 0, "TxPDO10"},
    {0x6000, 1, 21, 32, 0, "TxPDO11"},
    {0x6000, 1, 22, 32, 0, "TxPDO11"},
    {0x6000, 1, 23, 32, 0, "TxPDO12"},
    {0x6000, 1, 24, 32, 0, "TxPDO12"},
    {0x6000, 1, 25, 32, 0, "TxPDO13"},
    {0x6000, 1, 26, 32, 0, "TxPDO13"},
    {0x6000, 1, 27, 32, 0, "TxPDO14"},
    {0x6000, 1, 28, 32, 0, "TxPDO14"},
    {0x6000, 1, 29, 32, 0, "TxPDO15"},
    {0x6000, 1, 30, 32, 0, "TxPDO15"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_dnslave_rx_entries[] = {
    {0x7000, 1, 1, 32, 0, "RxPDO01"},
    {0x7000, 1, 2, 32, 0, "RxPDO01"},
    {0x7000, 1, 3, 32, 0, "RxPDO02"},
    {0x7000, 1, 4, 32, 0, "RxPDO02"},
    {0x7000, 1, 5, 32, 0, "RxPDO03"},
    {0x7000, 1, 6, 32, 0, "RxPDO03"},
    {0x7000, 1, 7, 32, 0, "RxPDO04"},
    {0x7000, 1, 8, 32, 0, "RxPDO04"},
    {0x7000, 1, 9, 32, 0, "RxPDO05"},
    {0x7000, 1, 10, 32, 0, "RxPDO05"},
    {0x7000, 1, 11, 32, 0, "RxPDO06"},
    {0x7000, 1, 12, 32, 0, "RxPDO06"},
    {0x7000, 1, 13, 32, 0, "RxPDO07"},
    {0x7000, 1, 14, 32, 0, "RxPDO07"},
    {0x7000, 1, 15, 32, 0, "RxPDO08"},
    {0x7000, 1, 16, 32, 0, "RxPDO08"},
    {0x7000, 1, 17, 32, 0, "RxPDO09"},
    {0x7000, 1, 18, 32, 0, "RxPDO09"},
    {0x7000, 1, 19, 32, 0, "RxPDO010"},
    {0x7000, 1, 20, 32, 0, "RxPDO010"},
    {0x7000, 1, 21, 32, 0, "RxPDO011"},
    {0x7000, 1, 22, 32, 0, "RxPDO011"},
    {0x7000, 1, 23, 32, 0, "RxPDO012"},
    {0x7000, 1, 24, 32, 0, "RxPDO012"},
    {0x7000, 1, 25, 32, 0, "RxPDO013"},
    {0x7000, 1, 26, 32, 0, "RxPDO013"},
    {0x7000, 1, 27, 32, 0, "RxPDO014"},
    {0x7000, 1, 28, 32, 0, "RxPDO014"},
    {0x7000, 1, 29, 32, 0, "RxPDO015"},
    {0x7000, 1, 30, 32, 0, "RxPDO015"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_2hc_tx_entries[] = {
    {0x6000, 1, 1, 8, 0, "2HC CH0 Encoder status"},
    {0x6000, 1, 2, 8, 0, "2HC CH0 DI status"},
    {0x6000, 1, 3, 8, 0, "2HC CH0 DO status"},
    {0x6000, 1, 4, 8, 0, "2HC CH0 Compare status"},
    {0x6000, 1, 5, 32, 0, "2HC CH0 Probe status"},
    {0x6000, 1, 6, 32, 0, "2HC CH0 Encoder present position"},
    {0x6000, 1, 7, 32, 0, "2HC CH0 Measure value 1"},
    {0x6000, 1, 8, 32, 0, "2HC CH0 Measure value 2"},
    {0x6000, 1, 9, 32, 0, "2HC CH0 Probe 0 positive value"},
    {0x6000, 1, 10, 32, 0, "2HC CH0 Probe 1 positive value"},
    {0x6000, 1, 11, 32, 1, "2HC CH0 Reserve600"},
    {0x6000, 1, 12, 32, 1, "2HC CH0 Reserve601"},
    {0x6000, 1, 13, 32, 0, "2HC CH0 Probe 0 negative value"},
    {0x6000, 1, 14, 32, 0, "2HC CH0 Probe 1 negative value"},
    {0x6000, 1, 15, 32, 1, "2HC CH0 Reserve602"},
    {0x6000, 1, 16, 32, 1, "2HC CH0 Reserve603"},
    {0x6000, 1, 17, 32, 0, "2HC CH0 Errorcode"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_2hc_rx_entries[] = {
    {0x7000, 1, 1, 16, 0, "2HC CH0 Encoder command value"},
    {0x7000, 1, 2, 16, 0, "2HC CH0 DO function command value"},
    {0x7000, 1, 3, 32, 0, "2HC CH0 Encoder preset value"},
    {0x7000, 1, 4, 32, 0, "2HC CH0 Probe function command value"},
    {0x7000, 1, 5, 32, 0, "2HC CH0 Compare function command value"},
    {0x7000, 1, 6, 16, 0, "2HC CH0 Compare 0 command size/step"},
    {0x7000, 1, 7, 16, 1, "2HC CH0 Reserve700"},
    {0x7000, 1, 8, 16, 1, "2HC CH0 Reserve701"},
    {0x7000, 1, 9, 16, 1, "2HC CH0 Reserve702"},
    {0x7000, 1, 10, 32, 0, "2HC CH0 Compare 0 position value 1"},
    {0x7000, 1, 11, 32, 1, "2HC CH0 Reserve703"},
    {0x7000, 1, 12, 32, 1, "2HC CH0 Reserve704"},
    {0x7000, 1, 13, 32, 1, "2HC CH0 Reserve705"},
    {0x7000, 1, 14, 32, 0, "2HC CH0 Compare 0 position value 2"},
    {0x7000, 1, 15, 32, 1, "2HC CH0 Reserve706"},
    {0x7000, 1, 16, 32, 1, "2HC CH0 Reserve707"},
    {0x7000, 1, 17, 32, 1, "2HC CH0 Reserve708"},
    {0x7000, 1, 18, 32, 0, "2HC CH0 Compare function command parameter"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_2scom_mdb_tx_entries[] = {
    {0x6000, 1, 1, 240, 0, "2SCOM-MDB_Frame0_RX_0"},
    {0x6000, 1, 2, 240, 0, "2SCOM-MDB_Frame0_RX_1"},
    {0x6000, 1, 3, 240, 0, "2SCOM-MDB_Frame0_RX_2"},
    {0x6000, 1, 4, 240, 0, "2SCOM-MDB_Frame0_RX_3"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_2scom_mdb_rx_entries[] = {
    {0x7000, 1, 1, 240, 0, "2SCOM-MDB_Frame0_TX_0"},
    {0x7000, 1, 2, 240, 0, "2SCOM-MDB_Frame0_TX_1"},
    {0x7000, 1, 3, 240, 0, "2SCOM-MDB_Frame0_TX_2"},
    {0x7000, 1, 4, 240, 0, "2SCOM-MDB_Frame0_TX_3"},
};

static const lcec_mdp_pdo_entry_t gl20_gl20_2s485_mdb_tx_entries[] = {
    {0x6000, 1, 1, 240, 0, "2S485-MDB_Frame0_RX_0"},
    {0x6000, 1, 2, 240, 0, "2S485-MDB_Frame0_RX_1"},
    {0x6000, 1, 3, 240, 0, "2S485-MDB_Frame0_RX_2"},
    {0x6000, 1, 4, 240, 0, "2S485-MDB_Frame0_RX_3"},
};
static const lcec_mdp_pdo_entry_t gl20_gl20_2s485_mdb_rx_entries[] = {
    {0x7000, 1, 1, 240, 0, "2S485-MDB_Frame0_TX_0"},
    {0x7000, 1, 2, 240, 0, "2S485-MDB_Frame0_TX_1"},
    {0x7000, 1, 3, 240, 0, "2S485-MDB_Frame0_TX_2"},
    {0x7000, 1, 4, 240, 0, "2S485-MDB_Frame0_TX_3"},
};

static const lcec_mdp_module_t gl20_modules[] = {
    {0x10f41064, "GL20(GL20S)-0404ETP-5V", LCEC_MDP_MOD_DOUT, 0x1a01, 1, gl20_gl20_gl20s__0404etp_5v_tx_entries, 1, 0x1601, 1, gl20_gl20_gl20s__0404etp_5v_rx_entries, 1},  // NOTE: ESI offers 4tx/3rx alternative mappings; default (first) emitted
    {0x10f41060, "GL20(GL20S)-0808ETN", LCEC_MDP_MOD_DOUT, 0x1a01, 1, gl20_gl20_gl20s__0808etn_tx_entries, 1, 0x1601, 1, gl20_gl20_gl20s__0808etn_rx_entries, 1},  // NOTE: ESI offers 4tx/3rx alternative mappings; default (first) emitted
    {0x10f41061, "GL20(GL20S)-3232ETN", LCEC_MDP_MOD_DOUT, 0x1a01, 1, gl20_gl20_gl20s__3232etn_tx_entries, 4, 0x1601, 1, gl20_gl20_gl20s__3232etn_rx_entries, 4},  // NOTE: ESI offers 4tx/3rx alternative mappings; default (first) emitted
    {0x10f41523, "GL20(GL20S)-0032ETP", LCEC_MDP_MOD_DOUT, 0x1a04, 1, gl20_gl20_gl20s__0032etp_tx_entries, 5, 0x1601, 1, gl20_gl20_gl20s__0032etp_rx_entries, 4},  // NOTE: ESI offers 1tx/3rx alternative mappings; default (first) emitted
    {0x10f41521, "GL20(GL20S)-0032ETP-M", LCEC_MDP_MOD_DOUT, 0x1a04, 1, gl20_gl20_gl20s__0032etp_m_tx_entries, 5, 0x1601, 1, gl20_gl20_gl20s__0032etp_m_rx_entries, 4},  // NOTE: ESI offers 1tx/3rx alternative mappings; default (first) emitted
    {0x10f41011, "GL20(GL20S)-3200END", LCEC_MDP_MOD_DIN, 0x1a01, 1, gl20_gl20_gl20s__3200end_tx_entries, 4, 0, 0, NULL, 0},  // NOTE: ESI offers 4tx/0rx alternative mappings; default (first) emitted
    {0x10f41021, "GL20(GL20S)-0032ETN", LCEC_MDP_MOD_DOUT, 0x1a04, 1, gl20_gl20_gl20s__0032etn_tx_entries, 5, 0x1601, 1, gl20_gl20_gl20s__0032etn_rx_entries, 4},  // NOTE: ESI offers 1tx/3rx alternative mappings; default (first) emitted
    {0x10f41023, "GL20(GL20S)-0008ER", LCEC_MDP_MOD_DOUT, 0x1a04, 1, gl20_gl20_gl20s__0008er_tx_entries, 2, 0x1601, 1, gl20_gl20_gl20s__0008er_rx_entries, 1},  // NOTE: ESI offers 1tx/3rx alternative mappings; default (first) emitted
    {0x10f41027, "GL20(GL20S)-0004ER", LCEC_MDP_MOD_DOUT, 0x1a04, 1, gl20_gl20_gl20s__0004er_tx_entries, 2, 0x1601, 1, gl20_gl20_gl20s__0004er_rx_entries, 1},  // NOTE: ESI offers 1tx/3rx alternative mappings; default (first) emitted
    {0x10f41028, "GL20(GL20S)-0004ETP-2A", LCEC_MDP_MOD_DOUT, 0x1a04, 1, gl20_gl20_gl20s__0004etp_2a_tx_entries, 5, 0x1601, 1, gl20_gl20_gl20s__0004etp_2a_rx_entries, 1},  // NOTE: ESI offers 1tx/3rx alternative mappings; default (first) emitted
    {0x10f41022, "GL20(GL20S)-0008ETN", LCEC_MDP_MOD_DOUT, 0x1a04, 1, gl20_gl20_gl20s__0008etn_tx_entries, 2, 0x1601, 1, gl20_gl20_gl20s__0008etn_rx_entries, 1},  // NOTE: ESI offers 1tx/3rx alternative mappings; default (first) emitted
    {0x10f41025, "GL20(GL20S)-0008ETP", LCEC_MDP_MOD_DOUT, 0x1a04, 1, gl20_gl20_gl20s__0008etp_tx_entries, 2, 0x1601, 1, gl20_gl20_gl20s__0008etp_rx_entries, 1},  // NOTE: ESI offers 1tx/3rx alternative mappings; default (first) emitted
    {0x10f41010, "GL20(GL20S)-1600END", LCEC_MDP_MOD_DIN, 0x1a01, 1, gl20_gl20_gl20s__1600end_tx_entries, 2, 0, 0, NULL, 0},  // NOTE: ESI offers 4tx/0rx alternative mappings; default (first) emitted
    {0x10f41013, "GL20(GL20S)-1600END-5V", LCEC_MDP_MOD_DIN, 0x1a01, 1, gl20_gl20_gl20s__1600end_5v_tx_entries, 2, 0, 0, NULL, 0},  // NOTE: ESI offers 4tx/0rx alternative mappings; default (first) emitted
    {0x10f41012, "GL20(GL20S)-0800END", LCEC_MDP_MOD_DIN, 0x1a01, 1, gl20_gl20_gl20s__0800end_tx_entries, 1, 0, 0, NULL, 0},  // NOTE: ESI offers 4tx/0rx alternative mappings; default (first) emitted
    {0x10f41211, "GL20(GL20S)-0800ENA", LCEC_MDP_MOD_DIN, 0x1a01, 1, gl20_gl20_gl20s__0800ena_tx_entries, 1, 0, 0, NULL, 0},  // NOTE: ESI offers 4tx/0rx alternative mappings; default (first) emitted
    {0x10f41020, "GL20(GL20S)-0016ETN", LCEC_MDP_MOD_DOUT, 0x1a04, 1, gl20_gl20_gl20s__0016etn_tx_entries, 3, 0x1601, 1, gl20_gl20_gl20s__0016etn_rx_entries, 2},  // NOTE: ESI offers 1tx/3rx alternative mappings; default (first) emitted
    {0x10f41024, "GL20(GL20S)-0016ETP", LCEC_MDP_MOD_DOUT, 0x1a04, 1, gl20_gl20_gl20s__0016etp_tx_entries, 3, 0x1601, 1, gl20_gl20_gl20s__0016etp_rx_entries, 2},  // NOTE: ESI offers 1tx/3rx alternative mappings; default (first) emitted
    {0x10f41320, "GL20(GL20S)-0016ETP-5V", LCEC_MDP_MOD_DOUT, 0x1a04, 1, gl20_gl20_gl20s__0016etp_5v_tx_entries, 3, 0x1601, 1, gl20_gl20_gl20s__0016etp_5v_rx_entries, 2},  // NOTE: ESI offers 1tx/3rx alternative mappings; default (first) emitted
    {0x10f41031, "GL20(GL20S)-8ADV", LCEC_MDP_MOD_AIN, 0x1a02, 1, gl20_gl20_gl20s__8adv_tx_entries, 8, 0, 0, NULL, 0},  // NOTE: ESI offers 2tx/0rx alternative mappings; default (first) emitted
    {0x10f41032, "GL20(GL20S)-8ADI", LCEC_MDP_MOD_AIN, 0x1a02, 1, gl20_gl20_gl20s__8adi_tx_entries, 8, 0, 0, NULL, 0},  // NOTE: ESI offers 2tx/0rx alternative mappings; default (first) emitted
    {0x10f41030, "GL20(GL20S)-4AD", LCEC_MDP_MOD_AIN, 0x1a02, 1, gl20_gl20_gl20s__4ad_tx_entries, 4, 0, 0, NULL, 0},  // NOTE: ESI offers 2tx/0rx alternative mappings; default (first) emitted
    {0x10f41033, "GL20(GL20S)-4AD-H", LCEC_MDP_MOD_AIN, 0x1a02, 1, gl20_gl20_gl20s__4ad_h_tx_entries, 4, 0x1602, 1, gl20_gl20_gl20s__4ad_h_rx_entries, 1},  // NOTE: ESI offers 2tx/1rx alternative mappings; default (first) emitted
    {0x10f41041, "GL20(GL20S)-8DAV", LCEC_MDP_MOD_AOUT, 0x1a04, 1, gl20_gl20_gl20s__8dav_tx_entries, 9, 0x1602, 1, gl20_gl20_gl20s__8dav_rx_entries, 8},
    {0x10f41042, "GL20(GL20S)-8DAI", LCEC_MDP_MOD_AOUT, 0x1a04, 1, gl20_gl20_gl20s__8dai_tx_entries, 9, 0x1602, 1, gl20_gl20_gl20s__8dai_rx_entries, 8},
    {0x10f41040, "GL20(GL20S)-4DA", LCEC_MDP_MOD_AOUT, 0x1a04, 1, gl20_gl20_gl20s__4da_tx_entries, 5, 0x1602, 1, gl20_gl20_gl20s__4da_rx_entries, 4},
    {0x10f41050, "GL20(GL20S)-4PT", LCEC_MDP_MOD_OTHER, 0x1a03, 1, gl20_gl20_gl20s__4pt_tx_entries, 4, 0, 0, NULL, 0},  // NOTE: ESI offers 3tx/0rx alternative mappings; default (first) emitted
    {0x10f41055, "GL20(GL20S)-4PT-ISO", LCEC_MDP_MOD_OTHER, 0x1a03, 1, gl20_gl20_gl20s__4pt_iso_tx_entries, 4, 0x1602, 1, gl20_gl20_gl20s__4pt_iso_rx_entries, 1},  // NOTE: ESI offers 2tx/1rx alternative mappings; default (first) emitted
    {0x10f41051, "GL20(GL20S)-4TC", LCEC_MDP_MOD_OTHER, 0x1a03, 1, gl20_gl20_gl20s__4tc_tx_entries, 4, 0, 0, NULL, 0},  // NOTE: ESI offers 3tx/0rx alternative mappings; default (first) emitted
    {0x10f41056, "GL20(GL20S)-4TC-ISO", LCEC_MDP_MOD_OTHER, 0x1a03, 1, gl20_gl20_gl20s__4tc_iso_tx_entries, 4, 0x1602, 1, gl20_gl20_gl20s__4tc_iso_rx_entries, 1},  // NOTE: ESI offers 2tx/1rx alternative mappings; default (first) emitted
    {0x10f41053, "GL20(GL20S)-4LC-PID", LCEC_MDP_MOD_OTHER, 0x1a03, 1, gl20_gl20_gl20s__4lc_pid_tx_entries, 60, 0x1603, 1, gl20_gl20_gl20s__4lc_pid_rx_entries, 56},
    {0x10f41054, "GL20(GL20S)-8TC-PID", LCEC_MDP_MOD_OTHER, 0x1b00, 1, gl20_gl20_gl20s__8tc_pid_tx_entries, 120, 0x1700, 1, gl20_gl20_gl20s__8tc_pid_rx_entries, 96},
    {0x10f41052, "GL20(GL20S)-8TC", LCEC_MDP_MOD_OTHER, 0x1a03, 1, gl20_gl20_gl20s__8tc_tx_entries, 8, 0, 0, NULL, 0},
    {0x10f41080, "GL20(GL20S)-PS2", LCEC_MDP_MOD_OTHER, 0x1a04, 1, gl20_gl20_gl20s__ps2_tx_entries, 1, 0, 0, NULL, 0},
    {0x10f41090, "GL20-2CAN", LCEC_MDP_MOD_OTHER, 0x1b00, 1, gl20_gl20_2can_tx_entries, 30, 0x1700, 1, gl20_gl20_2can_rx_entries, 30},  // NOTE: ESI offers 3tx/2rx alternative mappings; default (first) emitted
    {0x10f41091, "GL20-2S485", LCEC_MDP_MOD_OTHER, 0x1a03, 1, gl20_gl20_2s485_tx_entries, 15, 0x1603, 1, gl20_gl20_2s485_rx_entries, 15},  // NOTE: ESI offers 2tx/1rx alternative mappings; default (first) emitted
    {0x10f41094, "GL20-2SCOM", LCEC_MDP_MOD_OTHER, 0x1a03, 1, gl20_gl20_2scom_tx_entries, 15, 0x1603, 1, gl20_gl20_2scom_rx_entries, 15},  // NOTE: ESI offers 2tx/1rx alternative mappings; default (first) emitted
    {0x10f41093, "GL20-2SSI", LCEC_MDP_MOD_OTHER, 0x1a03, 1, gl20_gl20_2ssi_tx_entries, 12, 0, 0, NULL, 0},  // NOTE: ESI offers 2tx/0rx alternative mappings; default (first) emitted
    {0x10f41095, "GL20-1DNM", LCEC_MDP_MOD_OTHER, 0x1b00, 1, gl20_gl20_1dnm_tx_entries, 30, 0x1700, 1, gl20_gl20_1dnm_rx_entries, 30},  // NOTE: ESI offers 2tx/1rx alternative mappings; default (first) emitted
    {0x10f41096, "GL20-DNSLAVE", LCEC_MDP_MOD_OTHER, 0x1b00, 1, gl20_gl20_dnslave_tx_entries, 30, 0x1700, 1, gl20_gl20_dnslave_rx_entries, 30},
    {0x10f41082, "GL20-2HC", LCEC_MDP_MOD_ENC, 0x1b00, 1, gl20_gl20_2hc_tx_entries, 17, 0x1700, 1, gl20_gl20_2hc_rx_entries, 18},  // NOTE: ESI offers 3tx/2rx alternative mappings; default (first) emitted
    {0x10f41098, "GL20-2SCOM-MDB", LCEC_MDP_MOD_OTHER, 0x1b00, 1, gl20_gl20_2scom_mdb_tx_entries, 4, 0x1700, 1, gl20_gl20_2scom_mdb_rx_entries, 4},  // NOTE: ESI offers 5tx/4rx alternative mappings; default (first) emitted
    {0x10f41099, "GL20-2S485-MDB", LCEC_MDP_MOD_OTHER, 0x1b00, 1, gl20_gl20_2s485_mdb_tx_entries, 4, 0x1700, 1, gl20_gl20_2s485_mdb_rx_entries, 4},  // NOTE: ESI offers 5tx/4rx alternative mappings; default (first) emitted
    {0, NULL, LCEC_MDP_MOD_OTHER, 0, 0, NULL, 0, 0, 0, NULL, 0},
};

static const lcec_mdp_family_t gl20_family = {
    .name = "gl20",
    .vid = 0x00100000,
    .pid = 0x10f41001,
    .revision = 0x01006000,
    .slot_index_incr = 0x40,
    .slot_pdo_incr = 8,
    .max_slots = 32,
    .download_ident_list = 1,
    .modules = gl20_modules,
};

#endif
